# Generated by Django 3.2.4 on 2021-06-05 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('incident_description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('incident_location', models.TextField()),
                ('initial_severity', models.CharField(max_length=255)),
                ('suspected_cause', models.TextField()),
                ('immediate_actions_taken', models.TextField()),
                ('sub_incident_type', models.TextField()),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
